# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "sugar")
Ingredient.create(name: "rum")
Ingredient.create(name: "bourbon")
Ingredient.create(name: "tonic")
Ingredient.create(name: "gin")
Ingredient.create(name: "lime")
Ingredient.create(name: "tequila")
Ingredient.create(name: "vodka")
Ingredient.create(name: "cider")
Ingredient.create(name: "lemonade")
Ingredient.create(name: "beer")
Ingredient.create(name: "coffee")
Ingredient.create(name: "ginger ale")
Ingredient.create(name: "champagne")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "triple sec")
Ingredient.create(name: "tomatoe juice")
Ingredient.create(name: "olive")
Ingredient.create(name: "vermouth")
Ingredient.create(name: "salt")
